---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-vip
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/kube-vip/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
