apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: minio
  name: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "5.0.11"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2023-06-29T05-12-28Z
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2023-06-28T21-54-17Z
    mode: standalone
    ignoreChartChecksums: true
    existingSecret: minio-root
    drivesPerNode: 1
    replicas: 1
    persistence:
      existingClaim: minio
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - s3.e3b0c442.dev
      tls:
        - hosts:
            - s3.e3b0c442.dev
          secretName: s3-e3b0c442-dev-tls
    consoleIngress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - minio.svc.e3b0c442.dev
      tls:
        - hosts:
            - minio.svc.e3b0c442.dev
          secretName: minio-svc-e3b0c424-dev-tls
    resources:
      requests:
        memory: 256Mi
    users: []
