apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.2
    path: /volume1/k8s/minio
  mountOptions:
    - nfsvers=4.2
    - nconnect=4
    - hard
    - noatime