---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  path: ./kubernetes/apps/kube-system/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m