---
- name: get the local username
  become: false
  local_action: command whoami
  register: local_username
  changed_when: False

- name: add SSH key
  authorized_key:
    user: "{{ local_username.stdout }}"
    key: "{{ lookup('file', 'ssh.pub') }}"
    state: present

- name: add local username to wheel
  user:
    name: "{{ local_username.stdout }}"
    groups: wheel
    append: yes

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: configure network
  include_tasks: network.yml

- name: ensure firewall is up
  service:
    name: firewalld
    state: started
    enabled: yes

- name: update all packages
  package:
    name: '*'
    state: latest

- name: install and configure gnupg
  include_tasks: gnupg.yml
  vars:
    username: "{{ local_username.stdout }}"

- name: install and configure zsh
  include_tasks: zsh.yml
  vars:
    username: "{{ local_username.stdout }}"

- name: setup SSH sudo
  include_tasks: ssh_sudo.yml