---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: pg-operator
  path: ./kubernetes/apps/gitea/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
