---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.svc.e3b0c442.dev
      tls: true
      tlsSecret: svc-e3b0c442-dev-tls
