---
- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250/tcp"
    - "8472/udp"
    - "179/tcp"

- name: create uninstall script
  copy:
    src: k3s-uninstall.sh
    dest: /usr/local/bin/k3s-uninstall.sh
    owner: root
    group: root
    mode: 0755

- name: create manifests directory
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory

- name: add kube-vip rbac manifest
  get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml

- name: add kube-vip deployment manifest
  template:
    src: kube-vip-deployment.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/kube-vip-deployment.yaml

- name: check if cluster is bootstrapped
  uri:
    url: "https://{{ kube_api_host }}:6443/readyz"
    status_code: 401
  register: k3s_cluster_bootstrap_check
  ignore_errors: true

- name: determine bootstrap status
  set_fact:
    k3s_cluster_bootstrapped: "{{ not k3s_cluster_bootstrap_check.failed }}"

- name: bootstrap cluster
  import_tasks: bootstrap.yml
  when: not k3s_cluster_bootstrapped
