---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: nick@e3b0c442.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "e3b0c442.dev"
            - "ourparadisefalls.com"
        dns01:
          cloudflare:
            email: nick@e3b0c442.dev
            apiTokenSecretRef:
              name: cf-api-token
              key: token
