---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teslamate
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/teslamate/teslamate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teslamate-grafana
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/teslamate/teslamate/grafana
  prune: true
  dependsOn:
    - name: teslamate
  sourceRef:
    kind: GitRepository
    name: flux-system
