apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: stackgres-operator
  name: stackgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: stackgres-operator
      version: "1.4.3"
      sourceRef:
        kind: HelmRepository
        name: stackgres
        namespace: flux-system
  values:
    adminui:
      service:
        exposeHTTP: true
    grafana:
      autoEmbed: true
      webHost: prometheus-grafana.prometheus
    authentication:
      secretRef:
        name: stackgres-restapi