---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mastodon
  namespace: flux-system
spec:
  path: ./kubernetes/apps/mastodon/mastodon/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
