---
- name: Create certbot directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/letsencrypt
    - /var/lib/letsencrypt
    - /var/log/letsencrypt

- name: Add certbot files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: cli.ini
      dest: /etc/letsencrypt/cli.ini
    - src: certbot
      dest: /etc/sysconfig/certbot
    - src: certbot-renew.service
      dest: /etc/systemd/system/certbot-renew.service
    - src: certbot-renew.timer
      dest: /etc/systemd/system/certbot-renew.timer

- name: Add cloudflare config
  template:
    src: cloudflare.ini.j2
    dest: /etc/letsencrypt/cloudflare.ini
    mode: 0600
    owner: root
    group: root
  vars:
    vault_master_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31633030303336393138316166643863303531346333666538653439366434353363306337326335
          3332396563356634343536633438613831346537643065610a626465396532653662636332393530
          61333166333466656338393230306336356334663739646139656235333464326433663238656436
          3837633033336438620a626137646636363239363231313437643032356230643062376362643330
          62633730386561383137333562636635396530653231616363653533356137383938

- name: Add posthook script
  copy:
    src: omada_certrotate.sh
    dest: /etc/letsencrypt/renewal-hooks/post/omada-controller.sh
    mode: 0755
    owner: root
    group: root

- name: check if ourparadisefalls.com certificate exists and is valid
  command: openssl verify -untrusted /etc/letsencrypt/live/ourparadisefalls.com/chain.pem /etc/letsencrypt/live/ourparadisefalls.com/cert.pem
  register: ourparadisefalls_cert

- name: get certificate if it isn't valid
  command: podman run --rm --name certbot -v "/etc/letsencrypt:/etc/letsencrypt:z" -v "/var/lib/letsencrypt:/var/lib/letsencrypt:z" docker.io/certbot/dns-cloudflare:latest certonly --dns-cloudflare-credentials=/etc/letsencrypt/cloudflare.ini -n --agree-tos -m nick@e3b0c442.dev --dns-cloudflare --domains '*.ourparadisefalls.com'           
  when: ourparadisefalls_cert.rc != 0

- name: enable certbot-renew timer
  systemd:
    name: certbot-renew.timer
    enabled: yes
    state: started
