---
- name: Apply container host role
  import_role:
    name: container_host

- name: Create Omada data folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/tplink/EAPController/data
    - /opt/tplink/EAPController/logs
    - /opt/tplink/EAPController/cert

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "8088/tcp"
    - "8043/tcp"
    - "8843/tcp"
    - "27001/udp"
    - "29810-29814/udp"

- name: Set up certificate
  import_tasks: certificate.yml

- name: Add Omada Controller service
  copy:
    src: omada-controller.service
    dest: /etc/systemd/system/omada-controller.service
    mode: 0644
    owner: root
    group: root
  notify: Restart omada controller

- name: Enable and start Omada Controller service
  systemd:
    name: omada-controller.service
    enabled: yes
    state: started
    daemon_reload: yes
