apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: gitea
  name: gitea
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  values:
    image:
      repository: gitea/gitea
      tag: 1.19.3
    service:
      ssh:
        type: LoadBalancer
        loadBalancerIP: 10.227.176.227
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      ingressClassName: traefik
      hosts:
        - host: git.0x.e3b0c442.dev
          paths:
            - path: /
      tls:
        - hosts:
            - git.0x.e3b0c442.dev
          secretName: git-0x-e3b0c442-dev-tls
    persistence:
      enabled: true
      existingClaim: data-gitea-0
      size: 10Gi
      storageClass: longhorn
    gitea:
      admin:
        existingSecret: gitea-admin
      config:
        APP_NAME: e3b0c442 git
        server:
          ROOT_URL: https://git.0x.e3b0c442.dev
          PROTCOL: http
      additionalConfigFromEnvs:
        - name: GITEA__database__DB_TYPE
          value: postgres
        - name:GITEA__database__SSL_MODE
          value: require
        - name: GITEA__database__HOST
          valueFrom:
            secretKeyRef:
              name: gitea-db-pguser-gitea
              key: pgbouncer-host
        - name: GITEA__database__NAME
          valueFrom:
            secretKeyRef:
              name: gitea-db-pguser-gitea
              key: dbname
        - name: GITEA__database__USER
          valueFrom:
            secretKeyRef:
              name: gitea-db-pguser-gitea
              key: user
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-db-pguser-gitea
              key: password
        - name: GITEA__service__DISABLE_REGISTRATION
          value: "true"
    postgresql:
      enabled: false
    memcached:
      enabled: false
