apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitea
  name: data-gitea-0
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
