---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: op-connect
  namespace: op-connect
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://1password.github.io/connect-helm-charts/
      chart: connect
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: op-connect
        namespace: flux-system
  values:
    connect:
      api:
        imageRepository: 1password/connect-api
      sync:
        imageRepository: 1password/connect-sync
      version: "1.6.1"
    operator:
      create: true
      imageRepository: 1password/onepassword-operator
      version: "1.6.0"
