---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: redis-operator
  name: redis-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: "3.2.8"
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      tag: v1.2.4
    monitoring:
      enabled: true
      serviceMonitor: true
      prometheus:
        name: redis-operator