---
- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - "6443/tcp"
    - "2379-2380/tcp"
    - "10250/tcp"
    - "8472/udp"
    - "179/tcp"
