---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: minio
    - name: op-connect
  path: ./kubernetes/apps/docker-registry/docker-registry/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
