---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pg-operator
  namespace: pg-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: pg-operator
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values:
    watchAllNamespaces: true
    nodeSelector:
      kubernetes.io/arch: amd64