---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: docker-registry
  name: docker-registry
spec:
  interval: 5m
  chart:
    spec:
      chart: docker-registry
      version: 2.2.2
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  values:
    image:
      tag: "2.8.2"
    storage: s3
    secrets:
      s3:
        secretRef: docker-registry-s3
    s3:
      region: us-east-1
      regionEndpoint: http://minio.minio:9000
      bucket: docker-registry
      encrypt: false
      secure: false
    extraVolumeMounts:
      - name: docker-registry-htpasswd
        mountPath: /auth
    extraVolumes:
    - name: docker-registry-htpasswd
      secret:
        secretName: docker-registry-htpasswd
    extraEnvVars:
      - name: REGISTRY_AUTH
        value: "htpasswd"
      - name: REGISTRY_AUTH_HTPASSWD_REALM
        value: "Registry Realm"
      - name: REGISTRY_AUTH_HTPASSWD_PATH
        value: "/auth/htpasswd"