---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: op-connect
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/cert-manager/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
