---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: teslamate
  name: teslamate-db
spec:
  interval: 5m
  chart:
    spec:
      chart: pg-db
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: flux-system
  values:
    crVersion: 2.2.0
    postgresVersion: 15
