apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: teslamate
  name: teslamate
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: teslamate/teslamate
      tag: edge
    env:
      TZ: UTC
      ENCRYPTION_KEY: 
        valueFrom:
          secretKeyRef:
            name: teslamate-encryption-key
            key: key
      DATABASE_HOST:
        valueFrom:
          secretKeyRef:
            name: teslamate-db-pguser-teslamate
            key: host
      DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: teslamate-db-pguser-teslamate
            key: user
      DATABASE_PASS:
        valueFrom:
          secretKeyRef:
            name: teslamate-db-pguser-teslamate
            key: password
      DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: teslamate-db-pguser-teslamate
            key: dbname
      DISABLE_MQTT: "true"
      DATABASE_SSL: "true"
      DATABASE_SSL_CA_CERT_FILE: /pg-cert/ca.crt
    service:
      main:
        ports:
          http:
            port: 4000
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        ingressClassName: traefik
        hosts:
          - host: teslamate.svc.e3b0c442.dev
            paths:
              - path: /
        tls:
          - hosts:
              - teslamate.svc.e3b0c442.dev
            secretName: teslamate-svc-e3b0c442-dev-tls
    persistence:
      pg-cert:
        enabled: true
        type: secret
        name: teslamate-db-cluster-cert

