---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mastodon
  namespace: mastodon
spec:
  interval: 5m
  chart:
    spec:
      chart: ./
      sourceRef:
        kind: GitRepository
        name: mastodon-chart
        namespace: flux-system
  values:
    image:
      tag: "v4.1.2"
    mastodon:
      local_domain: e3b0c442.dev
      web_domain: mastodon.e3b0c442.dev
      s3:
        enabled: true
        existingSecret: mastodon-s3
        bucket: mastodon
        endpoint: http://minio.minio:9000
        hostname: minio.minio
        region: us-east-1
      limitedFederationMode: true
      
