apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: mastodon
  namespace: mastodon
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    storage:
      persistentVolumeClaim:
        metadata:
          name: mastodon-redis-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: longhorn
          