---
apiVersion: stackgres.io/v1beta1
kind: SGObjectStorage
metadata:
  name: postgres-mastodon-objectstorage
  namespace: mastodon
spec:
  type: s3Compatible
  s3Compatible:
    bucket: e3b0c442-postgres-mastodon-backup
    awsCredentials:
      secretKeySelectors:
        accessKeyId:
          key: s3-accessKey
          name: cloudflare-r2
        secretAccessKey:
          key: s3-secretKey
          name: cloudflare-r2
    region: auto
    endpoint: https://4871a91f82eb093a25cddb6b1b760ccf.r2.cloudflarestorage.com
