apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  name: postgres-mastodon-poolingconfig
  namespace: mastodon
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        default_pool_size: "1000"
        ignore_startup_parameters: extra_float_digits
        max_client_conn: "1000"
        max_db_connections: "0"
        max_user_connections: "0"
        pool_mode: session
