---
server_init_args: >-
  {% if ansible_hostname == hostvars[groups['k3s_server'][0]]['ansible_hostname'] %}
    --cluster-init
  {% else %}
    --server https://{{ hostvars[groups['master'][0]].k3s_node_ip | split(",") | first | ansible.utils.ipwrap }}:6443
  {% endif %}
  --token {{ k3s_token }}
  {{ extra_server_args | default('') }}