---
- hosts: all
  become: yes
  roles: 
    - role: ansible_setup
    - role: common

- hosts: dns_server
  become: yes
  roles:
    - role: dns_server

- hosts: dhcp_server
  become: yes
  roles:
    - role: dhcp_server

- hosts: k3s
  become: yes
  roles:
    - role: k3s
