---
- hosts: all
  become: yes
  roles: 
    - role: ansible_setup
      tags: ansible_setup
    - role: common
      tags: common

- hosts: dns_server
  become: yes
  roles:
    - role: dns_server
      tags: dns_server

- hosts: dhcp_server
  become: yes
  roles:
    - role: dhcp_server
      tags: dhcp_server

- hosts: avahi
  become: yes
  roles:
    - role: avahi
      tags: avahi

- hosts: k3s_server
  become: yes
  roles:
    - role: k3s_server
      tags: k3s_server

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/download
    - role: k3s/raspberrypi

- hosts: k3s_server
  become: yes
  roles:
    - role: k3s/server

- hosts: k3s_agent
  become: yes
  roles:
    - role: k3s/agent
