---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: teslamate
  name: teslamate-grafana
spec:
  selector:
    matchLabels:
      app: teslamate-grafana
  template:
    metadata:
      labels:
        app: teslamate-grafana
    spec:
      containers:
        - name: teslamate-grafana
          image: registry.e3b0c442.dev/teslamate/grafana:edge
          imagePullSecrets:
            - name: registry-e3b0c442-dev-credentials
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-pguser-teslamate
                  key: user
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-pguser-teslamate
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-pguser-teslamate
                  key: dbname
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-pguser-teslamate
                  key: host
            - name: DATABASE_SSL_MODE
              value: "require"
            - name: GF_SERVER_DOMAIN
              value: teslamate.e3b0c442.dev
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: teslamate-grafana
      restartPolicy: Always
      securityContext:
        fsGroup: 0
      volumes:
        - name: teslamate-grafana
          persistentVolumeClaim:
            claimName: teslamate-grafana
