apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: teslamate
  name: teslamate-grafana
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
