apiVersion: v1
kind: Service
metadata:
  namespace: teslamate
  name: teslamate-grafana
  labels:
    app: teslamate-grafana
spec:
  type: ClusterIP
  selector:
    app: teslamate-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
