---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: kube-system
data:
  config.yaml: |
    tunnel: e3b0c442-dev-k8s
    metrics: 0.0.0.0:2000
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    ingress:
    - hostname: "registry.e3b0c442.dev"
      service: http://docker-registry.docker-registry:5000
    - hostname: "teslamate.e3b0c442.dev"
      service: http://teslamate-grafana.teslamate:3000
      path: /grafana
      originRequest:
        access:
          required: true
          teamName: e3b0c442
          audTag:
            - aud1 0b063ad0cd73744edfeb995f38b9b3416428a8df6bfdb14abed408b5233003aa
    - hostname: "teslamate.e3b0c442.dev"
      service: http://teslamate.teslamate:4000
      originRequest:
        access:
          required: true
          teamName: e3b0c442
          audTag:
            - aud1 0b063ad0cd73744edfeb995f38b9b3416428a8df6bfdb14abed408b5233003aa
    - hostname: "s3.e3b0c442.dev"
      service: http://minio.minio:9000
    - hostname: "tesla"
    - service: http_status:404