---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: kube-system
data:
  config.yaml: |
    tunnel: e3b0c442-dev-k8s
    metrics: 0.0.0.0:2000
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    ingress:
    - hostname: "registry.e3b0c442.dev"
      service: http://docker-registry.docker-registry:5000
    - hostname: "paperless.e3b0c442.dev"
      service: http://paperless.paperless:8000
    - hostname: "teslamate.e3b0c442.dev"
      service: http://teslamate-grafana.teslamate:3000
      path: /grafana
    - hostname: "teslamate.e3b0c442.dev"
      service: http://teslamate.teslamate:4000
    - hostname: "s3.e3b0c442.dev"
      service: http://minio.minio:9000
    - service: http_status:404