---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: kube-system
data:
  config.yaml: |
    tunnel: e3b0c442-dev-k8s
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    ingress:
    - hostname: "*.e3b0c442.dev"
      service: http://traefik:80
    - service: http_status:404