---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-operator
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/apps/redis-operator/redis-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
