---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: paperless
  name: paperless
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: "1.14.5"
    env:
      COMPOSE_PROJECT_NAME: paperless
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_DBHOST: postgresql-primary
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS}
      PAPERLESS_PORT: 8000
      PAPERLESS_URL: https://paperless.ourparadisefalls.com
      PAPERLESS_CONSUMER_POLLING: "60"
      USERMAP_GID: 100
    service:
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: paperless.ourparadisefalls.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - paperless.ourparadisefalls.com
    persistence:
      data:
        enabled: true
        type: custom
        mountPath: /usr/src/paperless/data
        volumeSpec:
          nfs:
            path: /volume1/k8s/paperless/data
            server: 192.168.1.2
      media:
        enabled: true
        type: custom
        mountPath: /usr/src/paperless/media
        volumeSpec:
          nfs:
            path: /volume1/k8s/paperless/media
            server: 192.168.1.2
      consume:
        enabled: true
        type: custom
        mountPath: /usr/src/paperless/consume
        volumeSpec:
          nfs:
            path: /volume1/k8s/paperless/consume
            server: 192.168.1.2
      export:
        enabled: true
        type: custom
        mountPath: /usr/src/paperless/export
        volumeSpec:
          nfs:
            path: /volume1/k8s/paperless/export
            server: 192.168.1.2
